---
title: "Project 2: Estimation"
---

The normal distribution family is nearly complete. They have their parameter, standard deviation, which they received from the upper beings upon the creation of the normal model, and is all that they could ever ask for. However, they always felt like they were missing something. They couldn’t understand what it was that they were missing, as every time they tried to get to the bottom of it, their minds went blank. Bothered by this confusion, they consulted a magic deity, who revealed the problem to them. It turns out that the normal distribution family was missing an important parameter, the mean! The family was unable to determine what it was that they were missing because the mean was unknown to them. The value assigned to a being registers them to a family, but since they didn’t receive a mean with a value, its existence was forgotten, while the standard deviation was remembered because they knew its value. Distraught at this revelation, the family asked the deity what they could do to find their unknown mean. The deity explained to them that since the mean was not assigned a value immediately upon introduction to the family, they’ll have to find the best estimate for the unknown parameter. It likely won’t be the exact correct value, but if done correctly, the estimate should be good enough. The family was unsure how to do this, so the deity summoned a magic hand to help them.

The hand was at least 10 feet tall and had a purple sack around the stub that protruded from the end of its palm. The family and the giant limb exchanged pleasantries before the giant hand dropped the purple sack to the ground. The sack opened upon hitting the ground and an innumerable amount of gems with letters carved into them were revealed. The sack was never-ending, and the family could only make out some of the letters. They were able to see X1, X5, and Xn from where they were standing. The hand explained that the sack of gems represented identically and independently distributed random variables which represent a random sample from the population of the normal model that led to the existence of the family and its standard deviation. The hand explained that the random variable was going to be used to create an estimator needed to help find the estimate. The giant hand then emitted a vibrating sound and the ground shook, causing the sack to explode, leaving a wand in its place. The giant hand lifted the magic wand, introducing it as the Estimator31400. On the wand was a tiny number pad, which the giant hand explained was for changing the values of the function that powers the wand. One of those values pertained to the sample size. The family looked at the wand in awe, asking the giant hand what had just happened. The giant hand explained that it sacrificed the sack of gems to the deities of likelihood. The deities then gifted them the wand in return, having carved it out of one of their great logs. The giant hand went on to explain that when used, the wand derives the maximum likelihood estimator of the unknown mean by taking the random variables (the sack) and applying the magical power of the deity’s great log. The wand took the gems, which had numbers on the back of them that represented observed values from the random sample and maximized the function from the deities of likelihood so that the observed values were the most probable given the estimated parameter. It further explained that this was only one way that they could find an estimate for their missing parameter.

The family, still awestruck by this magic wand, asked the giant hand how to use it. The hand showed them that they could use the number pad to change the values of the given function to produce an estimate. As the family plugged the proper numbers in, the wand produced a ball of light. Within the light appeared a number: the estimate. The family felt a rush of excitement, finally able to see an estimate for the mean. The hand explained that the family ought to ensure that the estimator is a good estimator.

The air around the family picked up, and a huge gust of wind swept past them, momentarily disorienting them. When they regained their senses, another wand was in front of them, producing its own ball of light and number. The giant hand described this one as the method of moments estimator, which was produced by the deities of momentous. The giant hand explained that it was preferable to have two different estimators to compare, that way the family had more of a choice in how they wanted to find the estimate. In order to compare the two, the estimators had to go through a series of trials. The estimates made within the balls of light disappeared as the balls became blank slates, representing their respective estimators.

First was a test of bias. The goal of this trial is for the estimator to be considered unbiased rather than biased. If an estimator is biased, then the estimate produced would be poisoned and no good for the family. The family looked nervous about the prospect of a bad and poisoned estimate but the giant hand was quick to reassure them that they can make adjustments and find an unbiased estimator and that the estimator can be biased under some circumstances but an unbiased estimator is preferred for the sake of this trial.. First, what occurred was that the “great expectations” of both estimators were found.. The results were put up against the great mewling mu which represented the population parameter, and anything but a result of zero was to be marked for bias. Luckily for the family, both estimators were accepted as unbiased, as it appeared that the great expectations matched the mewling mu.

The second trial was a test of variance. Here, the family needed to find the balls of light as they shrunk to match the size of their respective variances and then line them up in a tray. The balls of light exploded into many balls of the same size.The family scrambled after the balls as they rolled around on the floor, only catching them after a few moments. It appeared to the family that the smaller balls of light came from the maximum likelihood estimator. When the family lined up the balls, they found that the smaller ones were closer together, as their size required less distance apart, while the larger balls of light were farther apart and thus a smaller amount of balls were able to fit inside the tray compared to the smaller balls, making the smaller balls the winner of this trial. The variance came with numerical values of course, and when the two were divided in order to find their relative efficiency, the giant hand found that the result came out larger than one, resulting in the maximum likelihood estimator being deemed more efficient as well.

The third trial was where variance and bias became entangled with one another, as the balls representing the variance and the biased values of their respective estimators combined with each other to create two giant bright lights. The two lights dimmed as the new values in newly created balls of light emerged, one smaller than the other. The smaller one, belonging to the maximum likelihood estimator, fit snugly in the palm of a family member’s hand, while the larger one was too big for comfort, resulting in the smaller one becoming the favored one.

The final trial required the use of the wands, as the family was instructed to change the sample size and observe the change in size of the balls of light. The giant hand wanted to test the consistency of each of the estimators to see how close to the mewling mu they could get. The family observed that as the sample size increased, both of the estimator’s variances became smaller. The giant hand told the family that the decrease in size was a good sign, as the estimators seem to be consistent and therefore close to the mewling mu.

At the end of the trials, the family decided that the maximum likelihood estimator is the best estimator of the two, and with a few adjustments to the wand, their hard work is rewarded with their new estimate for their no longer unknown parameter.
